// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizRT.Models;

namespace QuizRTapi.Migrations
{
    [DbContext(typeof(QuizRTContext))]
    partial class QuizRTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizRT.Models.Options", b =>
                {
                    b.Property<int>("OptionsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect");

                    b.Property<string>("OptionGiven");

                    b.Property<int>("QuestionsId");

                    b.HasKey("OptionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("OptionsT");
                });

            modelBuilder.Entity("QuizRT.Models.Questions", b =>
                {
                    b.Property<int>("QuestionsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categ");

                    b.Property<string>("QuestionGiven");

                    b.Property<string>("Topic");

                    b.HasKey("QuestionsId");

                    b.ToTable("QuestionsT");
                });

            modelBuilder.Entity("QuizRT.Models.QuizRTTemplate", b =>
                {
                    b.Property<int>("TempId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categ");

                    b.Property<string>("CategName");

                    b.Property<string>("SparQL");

                    b.Property<string>("Text");

                    b.Property<string>("Topic");

                    b.Property<string>("TopicName");

                    b.HasKey("TempId");

                    b.ToTable("QuizRTTemplateT");
                });

            modelBuilder.Entity("QuizRT.Models.Options", b =>
                {
                    b.HasOne("QuizRT.Models.Questions")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
